In [1]:
#import the data analysis modules
from pandas import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%pylab inline

Populating the interactive namespace from numpy and matplotlib


`%matplotlib` prevents importing * from pylab and numpy


In [2]:
#pandas data structures mainly Series and DataFrame 
#Series 
s = Series([1,3,5,np.nan,6,8]) #passing a list

In [3]:
print s

0     1
1     3
2     5
3   NaN
4     6
5     8
dtype: float64


In [5]:
number=['one','three','five','nan','six','eight']

In [7]:
#you can explicity give the index,by default the index will be numbered from 0 to len(series-1)
s=Series([1,3,5,np.nan,6,8],index=number) 

In [8]:
print s

one       1
three     3
five      5
nan     NaN
six       6
eight     8
dtype: float64


In [9]:
#date_range function is in pandas which creates the list of dates from start to start+periods
dates=date_range('20160216',periods=6)

In [10]:
print dates

DatetimeIndex(['2016-02-16', '2016-02-17', '2016-02-18', '2016-02-19',
               '2016-02-20', '2016-02-21'],
              dtype='datetime64[ns]', freq='D')


In [16]:
#create the DataFrame
#the DataFrame has three attributes index,columns,values
#np.random.randn(x,y) create the x rows and y columns random number 2D np.array
df=DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))

In [17]:
print df

                   A         B         C         D
2016-02-16 -0.777715  0.832819  0.308761  0.441936
2016-02-17 -0.480723 -1.293394  0.930980  0.414803
2016-02-18 -0.323725  0.207236 -0.079057  0.044622
2016-02-19 -0.911825 -0.443269  1.122244 -0.812158
2016-02-20  1.517761 -0.111079  0.345689  0.164318
2016-02-21 -1.142340  1.063549 -0.168490 -0.878292


In [18]:
#we can create the DataFrame from the pyhton dictionary
#the index is crated here by 'C' columns 
df2 = pd.DataFrame({ 'A' : 1.,
                     'B' : pd.Timestamp('20130102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                     'D' : np.array([3] * 4,dtype='int32'),
                     'E' : pd.Categorical(["test","train","test","train"]),
                     'F' : 'foo' })

In [19]:
print df2

   A          B  C  D      E    F
0  1 2013-01-02  1  3   test  foo
1  1 2013-01-02  1  3  train  foo
2  1 2013-01-02  1  3   test  foo
3  1 2013-01-02  1  3  train  foo


In [21]:
#we can performs several pandas dataframe function over df and df2
#print datatypes of the columns by dtypes property
print df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [26]:
#viewing the data
#head print first 5 row or complete dataframe if it has less than or equal to 5 row
print df.head()

                   A         B         C         D
2016-02-16 -0.777715  0.832819  0.308761  0.441936
2016-02-17 -0.480723 -1.293394  0.930980  0.414803
2016-02-18 -0.323725  0.207236 -0.079057  0.044622
2016-02-19 -0.911825 -0.443269  1.122244 -0.812158
2016-02-20  1.517761 -0.111079  0.345689  0.164318


In [27]:
#tail method print specified numbers of rows from the end
print df.tail(4)

                   A         B         C         D
2016-02-18 -0.323725  0.207236 -0.079057  0.044622
2016-02-19 -0.911825 -0.443269  1.122244 -0.812158
2016-02-20  1.517761 -0.111079  0.345689  0.164318
2016-02-21 -1.142340  1.063549 -0.168490 -0.878292


In [29]:
#print the attribute of dataframe 
print df.index

DatetimeIndex(['2016-02-16', '2016-02-17', '2016-02-18', '2016-02-19',
               '2016-02-20', '2016-02-21'],
              dtype='datetime64[ns]', freq='D')


In [30]:
print df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')


In [31]:
print df.values

[[-0.77771474  0.83281855  0.3087614   0.44193619]
 [-0.48072349 -1.29339381  0.93098043  0.41480339]
 [-0.32372488  0.20723631 -0.07905652  0.04462186]
 [-0.91182513 -0.44326922  1.12224416 -0.81215797]
 [ 1.51776148 -0.11107921  0.34568917  0.16431805]
 [-1.14233996  1.06354865 -0.1684899  -0.87829201]]


In [32]:
#Describe shows a quick statistic summary of your data
print df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.353094  0.042644  0.410021 -0.104128
std    0.962564  0.864691  0.522862  0.593684
min   -1.142340 -1.293394 -0.168490 -0.878292
25%   -0.878298 -0.360222  0.017898 -0.597963
50%   -0.629219  0.048079  0.327225  0.104470
75%   -0.362975  0.676423  0.784658  0.352182
max    1.517761  1.063549  1.122244  0.441936


In [33]:
#Transposing your data
print df.T

   2016-02-16  2016-02-17  2016-02-18  2016-02-19  2016-02-20  2016-02-21
A   -0.777715   -0.480723   -0.323725   -0.911825    1.517761   -1.142340
B    0.832819   -1.293394    0.207236   -0.443269   -0.111079    1.063549
C    0.308761    0.930980   -0.079057    1.122244    0.345689   -0.168490
D    0.441936    0.414803    0.044622   -0.812158    0.164318   -0.878292


In [36]:
#Sorting by an axis
print df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2016-02-16  0.441936  0.308761  0.832819 -0.777715
2016-02-17  0.414803  0.930980 -1.293394 -0.480723
2016-02-18  0.044622 -0.079057  0.207236 -0.323725
2016-02-19 -0.812158  1.122244 -0.443269 -0.911825
2016-02-20  0.164318  0.345689 -0.111079  1.517761
2016-02-21 -0.878292 -0.168490  1.063549 -1.142340


In [43]:
#Sorting by values
print df.sort(columns='B')

                   A         B         C         D
2016-02-17 -0.480723 -1.293394  0.930980  0.414803
2016-02-19 -0.911825 -0.443269  1.122244 -0.812158
2016-02-20  1.517761 -0.111079  0.345689  0.164318
2016-02-18 -0.323725  0.207236 -0.079057  0.044622
2016-02-16 -0.777715  0.832819  0.308761  0.441936
2016-02-21 -1.142340  1.063549 -0.168490 -0.878292


C:\Users\Ashutosh Pandey\Anaconda\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


In [44]:
#Selection in the dataframe
#print particular column
print df['A']

2016-02-16   -0.777715
2016-02-17   -0.480723
2016-02-18   -0.323725
2016-02-19   -0.911825
2016-02-20    1.517761
2016-02-21   -1.142340
Freq: D, Name: A, dtype: float64


In [46]:
#print first three rows
#simple slicing 
print df[0:3] 

                   A         B         C         D
2016-02-16 -0.777715  0.832819  0.308761  0.441936
2016-02-17 -0.480723 -1.293394  0.930980  0.414803
2016-02-18 -0.323725  0.207236 -0.079057  0.044622


In [48]:
#slice via index
print df['20160216':'20160219']

                   A         B         C         D
2016-02-16 -0.777715  0.832819  0.308761  0.441936
2016-02-17 -0.480723 -1.293394  0.930980  0.414803
2016-02-18 -0.323725  0.207236 -0.079057  0.044622
2016-02-19 -0.911825 -0.443269  1.122244 -0.812158


In [49]:
#Selection by Label
print df.loc[dates[0]]

A   -0.777715
B    0.832819
C    0.308761
D    0.441936
Name: 2016-02-16 00:00:00, dtype: float64


In [52]:
#here select all level : and the select A and B
#Selecting on a multi-axis by label
print df.loc[:,['A','B']]

                   A         B
2016-02-16 -0.777715  0.832819
2016-02-17 -0.480723 -1.293394
2016-02-18 -0.323725  0.207236
2016-02-19 -0.911825 -0.443269
2016-02-20  1.517761 -0.111079
2016-02-21 -1.142340  1.063549


In [54]:
#Showing label slicing, both endpoints are included
print df.loc['20160216':'20160219',['A','B']]

                   A         B
2016-02-16 -0.777715  0.832819
2016-02-17 -0.480723 -1.293394
2016-02-18 -0.323725  0.207236
2016-02-19 -0.911825 -0.443269


In [71]:
#For getting a scalar value
#getting the very firt value
print df.loc[dates[0],'A']
%timeit df.loc[dates[0],'A']

-0.777714742452
10000 loops, best of 3: 162 µs per loop


In [65]:
#For getting fast access to a scalar (equiv to the prior method)
#timeit return run time per loop
print df.at[dates[0],'A']
%timeit df.at[dates[0],'A']

-0.777714742452
The slowest run took 7.43 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 13.1 µs per loop


In [74]:
#Select via the position of the passed integers
print df.iloc[3]

A   -0.911825
B   -0.443269
C    1.122244
D   -0.812158
Name: 2016-02-19 00:00:00, dtype: float64


In [80]:
#Again slicing by integer value
#note iloc only takes integer
print df.iloc[3:5,0:2]

                   A         B
2016-02-19 -0.911825 -0.443269
2016-02-20  1.517761 -0.111079


In [81]:
#By lists of integer position locations, similar to the numpy/python style
print df.iloc[[1,2,4],[0,2]]

                   A         C
2016-02-17 -0.480723  0.930980
2016-02-18 -0.323725 -0.079057
2016-02-20  1.517761  0.345689


In [82]:
#For slicing rows explicitly
print df.iloc[1:3,:]

                   A         B         C         D
2016-02-17 -0.480723 -1.293394  0.930980  0.414803
2016-02-18 -0.323725  0.207236 -0.079057  0.044622


In [84]:
#For slicing columns explicitly
print df.iloc[:,1:3]

                   B         C
2016-02-16  0.832819  0.308761
2016-02-17 -1.293394  0.930980
2016-02-18  0.207236 -0.079057
2016-02-19 -0.443269  1.122244
2016-02-20 -0.111079  0.345689
2016-02-21  1.063549 -0.168490


In [88]:
#For getting a value explicitly
print df.iloc[1,1]
%timeit df.iloc[1,1]

-1.29339380635
10000 loops, best of 3: 114 µs per loop


In [89]:
#For getting fast access to a scalar (equiv to the prior method)
#note iloc is faster than loc 
print df.iat[1,1]
%timeit df.iat[1,1]

-1.29339380635
The slowest run took 8.63 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 7.08 µs per loop


In [93]:
#Using a single column’s values to select data.
print df[df.A > 0]

                   A         B         C         D
2016-02-20  1.517761 -0.111079  0.345689  0.164318


In [95]:
#A where operation for getting.
#get all positive value in the dataframe
print df[df > 0]

                   A         B         C         D
2016-02-16       NaN  0.832819  0.308761  0.441936
2016-02-17       NaN       NaN  0.930980  0.414803
2016-02-18       NaN  0.207236       NaN  0.044622
2016-02-19       NaN       NaN  1.122244       NaN
2016-02-20  1.517761       NaN  0.345689  0.164318
2016-02-21       NaN  1.063549       NaN       NaN


In [96]:
#copy one dataframe to another
df2 = df.copy()

In [100]:
#create new row and assign values explicitly
df2['E'] = ['one', 'one','two','three','four','three']

In [102]:
print df2

                   A         B         C         D      E
2016-02-16 -0.777715  0.832819  0.308761  0.441936    one
2016-02-17 -0.480723 -1.293394  0.930980  0.414803    one
2016-02-18 -0.323725  0.207236 -0.079057  0.044622    two
2016-02-19 -0.911825 -0.443269  1.122244 -0.812158  three
2016-02-20  1.517761 -0.111079  0.345689  0.164318   four
2016-02-21 -1.142340  1.063549 -0.168490 -0.878292  three


In [104]:
#select particular column and then select specific row
print df2[df2['E'].isin(['two','four'])]

                   A         B         C         D     E
2016-02-18 -0.323725  0.207236 -0.079057  0.044622   two
2016-02-20  1.517761 -0.111079  0.345689  0.164318  four


In [113]:
#Setting a new column automatically aligns the data by the indexes
s1 = Series([1,2,3,4,5,6], index=pd.date_range('20160216', periods=6))

In [114]:
print s1

2016-02-16    1
2016-02-17    2
2016-02-18    3
2016-02-19    4
2016-02-20    5
2016-02-21    6
Freq: D, dtype: int64


In [121]:
#assign a series as column to dataframe
df['F'] = s1

In [122]:
print df

                   A         B         C         D  F
2016-02-16  0.000000  0.832819  0.308761  0.441936  1
2016-02-17 -0.480723 -1.293394  0.930980  0.414803  2
2016-02-18 -0.323725  0.207236 -0.079057  0.044622  3
2016-02-19 -0.911825 -0.443269  1.122244 -0.812158  4
2016-02-20  1.517761 -0.111079  0.345689  0.164318  5
2016-02-21 -1.142340  1.063549 -0.168490 -0.878292  6


In [123]:
#reset value of df
df.at[dates[0],'A'] = 0

In [124]:
print df

                   A         B         C         D  F
2016-02-16  0.000000  0.832819  0.308761  0.441936  1
2016-02-17 -0.480723 -1.293394  0.930980  0.414803  2
2016-02-18 -0.323725  0.207236 -0.079057  0.044622  3
2016-02-19 -0.911825 -0.443269  1.122244 -0.812158  4
2016-02-20  1.517761 -0.111079  0.345689  0.164318  5
2016-02-21 -1.142340  1.063549 -0.168490 -0.878292  6


In [125]:
df.iat[0,1] = 0

In [127]:
print df

                   A         B         C         D  F
2016-02-16  0.000000  0.000000  0.308761  0.441936  1
2016-02-17 -0.480723 -1.293394  0.930980  0.414803  2
2016-02-18 -0.323725  0.207236 -0.079057  0.044622  3
2016-02-19 -0.911825 -0.443269  1.122244 -0.812158  4
2016-02-20  1.517761 -0.111079  0.345689  0.164318  5
2016-02-21 -1.142340  1.063549 -0.168490 -0.878292  6


In [130]:
#setting D column to 5 
df.loc[:,'D'] = np.array([5] * len(df))

In [131]:
print df

                   A         B         C  D  F
2016-02-16  0.000000  0.000000  0.308761  5  1
2016-02-17 -0.480723 -1.293394  0.930980  5  2
2016-02-18 -0.323725  0.207236 -0.079057  5  3
2016-02-19 -0.911825 -0.443269  1.122244  5  4
2016-02-20  1.517761 -0.111079  0.345689  5  5
2016-02-21 -1.142340  1.063549 -0.168490  5  6


In [134]:
#Missing Data
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E']) 

In [135]:
print df1

                   A         B         C  D  F   E
2016-02-16  0.000000  0.000000  0.308761  5  1 NaN
2016-02-17 -0.480723 -1.293394  0.930980  5  2 NaN
2016-02-18 -0.323725  0.207236 -0.079057  5  3 NaN
2016-02-19 -0.911825 -0.443269  1.122244  5  4 NaN


In [136]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [137]:
print df1

                   A         B         C  D  F   E
2016-02-16  0.000000  0.000000  0.308761  5  1   1
2016-02-17 -0.480723 -1.293394  0.930980  5  2   1
2016-02-18 -0.323725  0.207236 -0.079057  5  3 NaN
2016-02-19 -0.911825 -0.443269  1.122244  5  4 NaN


In [140]:
print df1.dropna(how='any')

                   A         B         C  D  F  E
2016-02-16  0.000000  0.000000  0.308761  5  1  1
2016-02-17 -0.480723 -1.293394  0.930980  5  2  1


In [142]:
print df1.fillna(value=5)

                   A         B         C  D  F  E
2016-02-16  0.000000  0.000000  0.308761  5  1  1
2016-02-17 -0.480723 -1.293394  0.930980  5  2  1
2016-02-18 -0.323725  0.207236 -0.079057  5  3  5
2016-02-19 -0.911825 -0.443269  1.122244  5  4  5


In [143]:
print pd.isnull(df1)

                A      B      C      D      F      E
2016-02-16  False  False  False  False  False  False
2016-02-17  False  False  False  False  False  False
2016-02-18  False  False  False  False  False   True
2016-02-19  False  False  False  False  False   True


In [144]:
#Stats
df.mean()

A   -0.223475
B   -0.096160
C    0.410021
D    5.000000
F    3.500000
dtype: float64

In [146]:
#Same operation on the other axis
df.mean(1)

2016-02-16    1.261752
2016-02-17    1.231373
2016-02-18    1.560891
2016-02-19    1.753430
2016-02-20    2.350474
2016-02-21    2.150544
Freq: D, dtype: float64

In [149]:
#Operating with objects that have different dimensionality and need alignment. In addition, pandas automatically broadcasts along the specified dimension
s = Series([1,3,5,np.nan,6,8], index=dates).shift(2)

In [154]:
s

2016-02-16   NaN
2016-02-17   NaN
2016-02-18     1
2016-02-19     3
2016-02-20     5
2016-02-21   NaN
Freq: D, dtype: float64

In [155]:
print df.sub(s, axis='index')

                   A         B         C   D   F
2016-02-16       NaN       NaN       NaN NaN NaN
2016-02-17       NaN       NaN       NaN NaN NaN
2016-02-18 -1.323725 -0.792764 -1.079057   4   2
2016-02-19 -3.911825 -3.443269 -1.877756   2   1
2016-02-20 -3.482239 -5.111079 -4.654311   0   0
2016-02-21       NaN       NaN       NaN NaN NaN


In [156]:
print df.apply(np.cumsum)

                   A         B         C   D   F
2016-02-16  0.000000  0.000000  0.308761   5   1
2016-02-17 -0.480723 -1.293394  1.239742  10   3
2016-02-18 -0.804448 -1.086157  1.160685  15   6
2016-02-19 -1.716273 -1.529427  2.282929  20  10
2016-02-20 -0.198512 -1.640506  2.628619  25  15
2016-02-21 -1.340852 -0.576957  2.460129  30  21


In [162]:
#lambda is similar to foreach in c# or auto in c++
#select max and min elements from each column and subtract 
print df
df.apply(lambda x: x.max() - x.min())

                   A         B         C  D  F
2016-02-16  0.000000  0.000000  0.308761  5  1
2016-02-17 -0.480723 -1.293394  0.930980  5  2
2016-02-18 -0.323725  0.207236 -0.079057  5  3
2016-02-19 -0.911825 -0.443269  1.122244  5  4
2016-02-20  1.517761 -0.111079  0.345689  5  5
2016-02-21 -1.142340  1.063549 -0.168490  5  6


A    2.660101
B    2.356942
C    1.290734
D    0.000000
F    5.000000
dtype: float64